[package]
name = "datavzrd"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>", "Felix Wiegand <felix.wiegand@tu-dortmund.de>"]
edition = "2021"

[dependencies]
derefable = "0.1"
serde = "1"
structopt = "0.3"
anyhow = "1"
thiserror = "1"
csv = "1.1"